version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/exercisefiles/node/"
      - "/exercisefiles/node_typescript/"
      - "/completesolution/node/"
      - "/completesolution/node_typescript/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directories:
      - "/exercisefiles/python/"
      - "/exercisefiles/python_dataengineer/"
      - "/exercisefiles/python_datascientist/"
      - "/completesolution/dataengineer/"
      - "/completesolution/datascientist/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directories:
      - "/exercisefiles/java_quarkus/"
      - "/exercisefiles/java_springboot/"
      - "/completesolution/java_quarkus/"
      - "/completesolution/java_springboot/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directories:
    - "/exercisefiles/dotnet/"
    - "/completesolution/dotnet/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "dotnet-sdk"
    directories:
    - "/exercisefiles/dotnet/"
    - "/completesolution/dotnet/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"